// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

import Logo from "./components/Logo";
import Navigation from "./components/Navigation";

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }

export const metadata = {
  title: "The Wild Oasis",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
          <Navigation />
        </header>
        <main>{children}</main>
        <footer>Copy right by the wild oasis</footer>
      </body>
    </html>
  );
}
